# Generated by Django 3.0.4 on 2020-04-01 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='url',
        ),
        migrations.AddField(
            model_name='feed',
            name='link',
            field=models.URLField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='title',
            field=models.CharField(max_length=63, null=True),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63)),
                ('description', models.TextField()),
                ('link', models.URLField(max_length=255)),
                ('pub_date', models.DateField(verbose_name='date published')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rss.Feed')),
            ],
            options={
                'ordering': ['-pub_date'],
                'get_latest_by': 'pub_date',
            },
        ),
    ]
