# Generated by Django 3.0.4 on 2020-04-01 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0002_auto_20200401_0201'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
