# Generated by Django 3.0.4 on 2020-05-10 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0003_delete_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feed',
            new_name='Newspaper',
        ),
    ]
